sudo: required
language: minimal

git:
  depth: 2

branches:
  only:
  - master
  - devel

services:
  - docker

env:
  global:
    - IMAGE_REPO=gcr.io/dd-decaf-cfbf6/id-mapper
    - IMAGE_TAG=${TRAVIS_BRANCH}
    - IMAGE=${IMAGE_REPO}:${IMAGE_TAG}

install:
  - docker build -t ${IMAGE_REPO}:${TRAVIS_COMMIT::12} -t ${IMAGE_REPO}:${TRAVIS_BRANCH} .
  - make setup

script:
  # Flake8 temporarily disabled until service is refreshed
  # - make flake8
  - make isort
  - make license
  - make safety
  - make test-travis
  - # Run the tests and report coverage (see https://docs.codecov.io/docs/testing-with-docker).
  - mkdir --parents /tmp/coverage
  - docker-compose run --rm -e ENVIRONMENT=testing -v "/tmp/coverage:/tmp/coverage" web pytest --cov-report "xml:/tmp/coverage/coverage.xml" --cov-report term --cov=src/id_mapper
  - bash <(curl -s https://codecov.io/bash) -f "/tmp/coverage/coverage.xml"

before_deploy:
  - ./scripts/install_gcloud.sh
  - ./scripts/install_kubectl.sh
  - docker push ${IMAGE_REPO}:${TRAVIS_COMMIT::12}
  - docker push ${IMAGE_REPO}:${TRAVIS_BRANCH}

deploy:
  provider: script
  script: ./scripts/deploy.sh
  on:
    all_branches: true

notifications:
  email: false
  slack:
    rooms:
      secure: "58HgbeojcuOWThc01T+YoB1Dkvc5wYRiiseUmahsDSHLXKzQLb55XhO+hHrEQo3/jZtWAGCkIKV0N5lZtIajAcREJMDCL2/WzhV1LKz8Aq594PgGwI+c8PEbb667X+sgPTrvibikAcepk5nRVbhkKOqkrIywYi6fzjJN+exzcbYv5Y7iNcmzDC92mIIhwA64EmN0BNVuTafVYK2iQKX/2nyS0HX/ptBuQXg+JtPVc/8dcmtTu6TrBQWTZvL5QUjFZeIBPj0nSrggiIoib8YfFnfLLPQevICMRo/ISz02M85XPsGcg3UYPJJjfsXlf7Q4f1iBc4v594UriNL5q7IDESdgUfMj/2eBlKg+c19QCot/KavCvTixOP1nzWcVJ2rBsfo39PYpZa70uhgMe0mhg8dhM/DoU7sxWHRMQ5M0AFJCkHJMoK1Wwqba7WTVhoRU09zt2ZDCV21wlQdt5gyVcqWoWtHouGHi6A4OpeCOToEZxi8Z73IBDKEi7fkEvGIgnA+gN+PkS0+2+NSfLpe3HW5LVUPU+gu+xQqdPC8ZCzLnBmJ9UOXindRWCPEMSl1xpXyeN8Z5qHMme7e0MKCM9GnJCSc3Gph67eAREJ6rD4hq4+OHYDnZAKSeHz6m2f3S6hs4jb/MkQuA+/jqt6qOOopCrH+XOwDAQdf0A8O2qC8="
    on_success: change
    on_failure: change
    on_pull_requests: false
