sudo: required
language: python
services:
- docker
before_install:
- docker login -e=$DOCKER_EMAIL -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
install:
- docker-compose up -d db
- sleep 30s
- docker-compose up -d web
script:
- docker-compose logs
- docker-compose exec web /bin/bash -c "py.test --cov=./id_mapper tests/"
- docker-compose logs
after_success:
- docker-compose exec web /bin/bash -c "codecov --token $CODECOV_TOKEN"
deploy:
  provider: script
  script: ./push_to_hub_travis.sh
  on:
    all_branches: true
