version: '2'
services:
  db:
    image: neo4j:3.1
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/1
  web:
    build:
      context: .
    ports:
      - 80:7000
    volumes:
      - .:/id_mapper
    depends_on:
      - db
    environment:
      - ID_MAPPER_API=${ID_MAPPER_API}
      - ID_MAPPER_PORT=${ID_MAPPER_PORT}
      - ID_MAPPER_PASSWORD=${ID_MAPPER_PASSWORD}
      - ID_MAPPER_USER=${ID_MAPPER_USER}
      - PYTHONASYNCIODEBUG=1
    restart: always
