db:
  image: neo4j:3.1
  ports:
    - 7474:7474
    - 7687:7687
#  volumes:
#    - '/usr/share/neo4j/data:/data'
web:
  build: .
  dockerfile: Dockerfile
  ports:
    - 80:7000
  links:
    - db
  environment:
    - PYTHONUNBUFFERED=1
    - PYTHONASYNCIODEBUG=1
